### ISSUE TITLE
[코테] Minimum Area Rectangle

### ISSUE THREAD

**Issue by anjdal713** [Team-Discipline/Coding-Test#187]
<p><strong>Minimum Area Rectangle (Medium)</strong><br><br></p>
<p>You are given an array of points in the <strong>X-Y plane</strong> <code>points</code> where <code>points[i] = [xi, yi]</code>.

<p>Return the minimum area of a rectangle formed from these points, with sides parallel to the X and Y axes. If there is not any such rectangle, return <code>0</code>.<br><br></p>

<p><strong class="example">Example 1:</strong></p>
<img alt="" src="https://assets.leetcode.com/uploads/2021/08/03/rec1.JPG" style="width: 500px; height: 447px;">
<pre><strong>Input:</strong> points = [[1,1],[1,3],[3,1],[3,3],[2,2]]
<strong>Output:</strong> 4
</pre>

<p><strong class="example">Example 2:</strong></p>
<img alt="" src="https://assets.leetcode.com/uploads/2021/08/03/rec2.JPG" style="width: 500px; height: 477px;">
<pre><strong>Input:</strong> points = [[1,1],[1,3],[3,1],[3,3],[4,1],[4,3]]
<strong>Output:</strong> 2
</pre>

<p>&nbsp;</p>
<p><strong>Constraints:</strong></p>

<ul>
	<li><code>1 &lt;= points.length &lt;= 500</code></li>
	<li><code>points[i].length == 2</code></li>
	<li><code>0 &lt;= x<sub>i</sub>, y<sub>i</sub> &lt;= 4 * 10<sup>4</sup></code></li>
	<li>All the given points are <strong>unique</strong>.</li>
</ul>

https://leetcode.com/problems/minimum-area-rectangle/

**Comment by anjdal713** [comment]
leetcode 문제 이쁘게 긁어오는 방법 없나? 몰라서 html 수작업했음........

**Comment by kreimben** [comment]
드래그 복붙
