### ISSUE TITLE
[코테] 옹알이(1)

### ISSUE THREAD

**Issue by JungHanLeee** [Team-Discipline/Coding-Test#241]
<html>
<body>
<div class="challenge-nav nav nav-tabs nav-tabs-dark task-tab" style="box-sizing: border-box; display: flex; flex-wrap: wrap; padding: 0px 1rem; margin-bottom: 0px; list-style: none; border-bottom: 0px; box-shadow: rgb(23, 35, 52) 0px -0.0625rem inset; background-color: rgb(38, 55, 71); position: relative; justify-content: space-between; height: 3.5rem; color: rgb(38, 55, 71); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="nav-item algorithm-nav-link algorithm-title" style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; margin-bottom: 0px; padding: 0.9375rem 0px 0px; color: white;"><span style="box-sizing: border-box; padding-bottom: 0.5rem;">옹알이 (1)</span></li><div class="nav-right-menu" style="box-sizing: border-box; display: flex; align-items: center;"><div class="challenge-settings nav-item" style="box-sizing: border-box; margin: 0px; display: flex; align-items: center; justify-content: flex-end; height: 3rem;"><div class="btn-group-theme btn-group btn-group-toggle" data-toggle="buttons" style="box-sizing: border-box; position: relative; display: inline-flex; vertical-align: middle; margin-left: 0.5rem;"><label class="btn btn-sm btn-outline-dark active" style="box-sizing: border-box; display: inline-block; margin-bottom: 0px; font-size: 0.75rem; line-height: 1.125rem; font-weight: 500; color: white; text-align: center; vertical-align: middle; user-select: none; background-color: rgb(68, 87, 108); border: 1px solid rgb(68, 87, 108); padding: 0.125rem 0.375rem; border-radius: 0.2rem 0px 0px 0.2rem; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; z-index: 1;"><input type="radio" name="themes" autocomplete="off" checked="" data-toggle="button" data-theme="dark" style="box-sizing: border-box; margin: 0px 0.375rem 0px 0px; font-family: inherit; font-size: inherit; line-height: inherit; overflow: visible; padding: 0px; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.32rem solid rgb(38, 55, 71); appearance: none; background-color: white !important; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">dark</label><label class="btn btn-sm btn-outline-dark" style="box-sizing: border-box; display: inline-block; margin-bottom: 0px; font-size: 0.75rem; line-height: 1.125rem; font-weight: 500; color: rgb(68, 87, 108); text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(68, 87, 108); padding: 0.125rem 0.375rem; border-radius: 0px 0.2rem 0.2rem 0px; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; margin-left: -1px;"><input type="radio" name="themes" autocomplete="off" data-toggle="button" data-theme="light" style="box-sizing: border-box; margin: 0px 0.375rem 0px 0px; font-family: inherit; font-size: inherit; line-height: inherit; overflow: visible; padding: 0px; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.125rem solid rgb(178, 192, 204); appearance: none; background-color: transparent; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">light</label></div><div data-toggle="popover" data-trigger="hover" data-placement="bottom" data-content="코드 에디터의 단축키를 설정하는 옵션입니다. 선호하는 에디터 옵션이 없다면 sublime을 선택해주세요." data-original-title="" title="" style="box-sizing: border-box;"><div class="btn-group-keymap btn-group btn-group-toggle" data-toggle="buttons" style="box-sizing: border-box; position: relative; display: inline-flex; vertical-align: middle; margin-left: 0.5rem;"><label class="btn btn-sm btn-outline-dark active" style="box-sizing: border-box; display: inline-block; margin-bottom: 0px; font-size: 0.75rem; line-height: 1.125rem; font-weight: 500; color: white; text-align: center; vertical-align: middle; user-select: none; background-color: rgb(68, 87, 108); border: 1px solid rgb(68, 87, 108); padding: 0.125rem 0.375rem; border-radius: 0.2rem 0px 0px 0.2rem; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; z-index: 1;"><input type="radio" name="keymaps" autocomplete="off" checked="" data-keymap="sublime" style="box-sizing: border-box; margin: 0px 0.375rem 0px 0px; font-family: inherit; font-size: inherit; line-height: inherit; overflow: visible; padding: 0px; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.32rem solid rgb(38, 55, 71); appearance: none; background-color: white !important; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">sublime</label><label class="btn btn-sm btn-outline-dark" style="box-sizing: border-box; display: inline-block; margin-bottom: 0px; font-size: 0.75rem; line-height: 1.125rem; font-weight: 500; color: rgb(68, 87, 108); text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(68, 87, 108); padding: 0.125rem 0.375rem; border-radius: 0px; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; margin-left: -1px;"><input type="radio" name="keymaps" autocomplete="off" data-keymap="vim" style="box-sizing: border-box; margin: 0px 0.375rem 0px 0px; font-family: inherit; font-size: inherit; line-height: inherit; overflow: visible; padding: 0px; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.125rem solid rgb(178, 192, 204); appearance: none; background-color: transparent; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">vim</label><label class="btn btn-sm btn-outline-dark" style="box-sizing: border-box; display: inline-block; margin-bottom: 0px; font-size: 0.75rem; line-height: 1.125rem; font-weight: 500; color: rgb(68, 87, 108); text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(68, 87, 108); padding: 0.125rem 0.375rem; border-radius: 0px 0.2rem 0.2rem 0px; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; margin-left: -1px;"><input type="radio" name="keymaps" autocomplete="off" data-keymap="emacs" style="box-sizing: border-box; margin: 0px 0.375rem 0px 0px; font-family: inherit; font-size: inherit; line-height: inherit; overflow: visible; padding: 0px; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.125rem solid rgb(178, 192, 204); appearance: none; background-color: transparent; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">emacs</label></div></div><div class="dropdown-language" id="tour7" style="box-sizing: border-box; margin-left: 0.5rem;"><button class="btn btn-sm btn-dark dropdown-toggle" type="button" data-toggle="dropdown" style="box-sizing: border-box; border-radius: 0.2rem; margin: 0px; font-family: inherit; font-size: 0.75rem; line-height: 1.125rem; overflow: visible; text-transform: none; appearance: button; display: inline-block; font-weight: 500; color: white; text-align: center; vertical-align: middle; user-select: none; background-color: rgb(68, 87, 108); border: 1px solid rgb(68, 87, 108); padding: 0.125rem 0.375rem; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; white-space: nowrap; cursor: pointer;">Python3<span> </span></button></div></div></div></div><div class="challenge-content-wrap js-challenge-content-wrap" style="box-sizing: border-box; position: relative; color: rgb(38, 55, 71); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div data-tryout-id="85889" data-tryout-token-id="2650656" data-tryout-category="school_practice" data-tryout-challenge-id="210107" data-interact-mode="testing_and_scoring" data-challengeable-type="algorithm" data-challengeable-id="14754" data-tour-mode="general" data-clipboard-restricted="false" data-user-name="por-sche" data-is-interviewer="false" data-scoring-unit="testcase" data-course-id="17584" data-lesson-id="197235" data-lesson-type="Practice" data-next-lesson-id="197236" data-language="python3" data-algorithm-type="standard" data-interface-type="function" data-lesson-comment-activation-score="30" data-is-lesson="true" class="challenge-content  lesson-content lesson-algorithm-main-section" style="box-sizing: border-box; min-height: 31.25rem; background-color: rgb(38, 55, 71);"><div class="main-section false" style="box-sizing: border-box; display: flex; flex-direction: row; height: calc(100vh - 10rem);"><div class="guide-section false" id="tour2" style="box-sizing: border-box; overflow-y: auto; padding: 1rem; background-color: rgb(38, 55, 71); width: calc(40% - 12px);"><div class="guide-section-description" style="box-sizing: border-box;"><h6 class="guide-section-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-weight: 700; line-height: 1.5; font-size: 14px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; -webkit-font-smoothing: antialiased;">문제 설명</h6><div class="markdown solarized-dark" style="box-sizing: border-box; background-color: transparent; word-break: normal; overflow-wrap: break-word; color: rgb(178, 192, 204);"><p style="box-sizing: border-box; margin: 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">머쓱이는 태어난 지 6개월 된 조카를 돌보고 있습니다. 조카는 아직 "aya", "ye", "woo", "ma" 네 가지 발음을 최대 한 번씩 사용해 조합한(이어 붙인) 발음밖에 하지 못합니다. 문자열 배열<span> </span><code style="box-sizing: border-box; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-size: 14px; color: rgb(205, 215, 224); overflow-wrap: break-word; padding: 2px 6px; border: 1px solid rgb(23, 35, 52); margin: 0px 2px 0px 0px; background-color: rgb(32, 43, 61); border-radius: 0.25rem;">babbling</code>이 매개변수로 주어질 때, 머쓱이의 조카가 발음할 수 있는 단어의 개수를 return하도록 solution 함수를 완성해주세요.</p><hr style="box-sizing: content-box; height: 0px; overflow: visible; margin: 1.5rem 0px; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">제한사항</h5><ul style="box-sizing: border-box; margin: 0.75rem 0px 0px; padding-left: 2.5rem;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit;">1 ≤<span> </span><code style="box-sizing: border-box; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-size: 14px; color: rgb(205, 215, 224); overflow-wrap: break-word; padding: 2px 6px; border: 1px solid rgb(23, 35, 52); margin: 0px 2px 0px 0px; background-color: rgb(32, 43, 61); border-radius: 0.25rem;">babbling</code>의 길이 ≤ 100</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit; margin-top: 0.5rem;">1 ≤<span> </span><code style="box-sizing: border-box; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-size: 14px; color: rgb(205, 215, 224); overflow-wrap: break-word; padding: 2px 6px; border: 1px solid rgb(23, 35, 52); margin: 0px 2px 0px 0px; background-color: rgb(32, 43, 61); border-radius: 0.25rem;">babbling[i]</code>의 길이 ≤ 15</li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit; margin-top: 0.5rem;"><code style="box-sizing: border-box; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-size: 14px; color: rgb(205, 215, 224); overflow-wrap: break-word; padding: 2px 6px; border: 1px solid rgb(23, 35, 52); margin: 0px 2px 0px 0px; background-color: rgb(32, 43, 61); border-radius: 0.25rem;">babbling</code>의 각 문자열에서 "aya", "ye", "woo", "ma"는 각각 최대 한 번씩만 등장합니다.<ul style="box-sizing: border-box; margin: 0.75rem 0px 0px; padding-left: 2.5rem;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit;">즉, 각 문자열의 가능한 모든 부분 문자열 중에서 "aya", "ye", "woo", "ma"가 한 번씩만 등장합니다.</li></ul></li><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit; margin-top: 0.5rem;">문자열은 알파벳 소문자로만 이루어져 있습니다.</li></ul><hr style="box-sizing: content-box; height: 0px; overflow: visible; margin: 1.5rem 0px; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">입출력 예</h5>

babbling | result
-- | --
["aya", "yee", "u", "maa", "wyeoo"] | 1
["ayaye", "uuuma", "ye", "yemawoo", "ayaa"] | 3

<hr style="box-sizing: content-box; height: 0px; overflow: visible; margin: 1.5rem 0px; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">입출력 예 설명</h5><p style="box-sizing: border-box; margin: 0.75rem 0px 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">입출력 예 #1</p><ul style="box-sizing: border-box; margin: 1rem 0px 0px; padding-left: 2.5rem;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit;">["aya", "yee", "u", "maa", "wyeoo"]에서 발음할 수 있는 것은 "aya"뿐입니다. 따라서 1을 return합니다.</li></ul><p style="box-sizing: border-box; margin: 0.75rem 0px 0px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-weight: 400; letter-spacing: -0.1px; line-height: 1.8; overflow-wrap: break-word;">입출력 예 #2</p><ul style="box-sizing: border-box; margin: 1rem 0px 0px; padding-left: 2.5rem;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit;">["ayaye", "uuuma", "ye", "yemawoo", "ayaa"]에서 발음할 수 있는 것은 "aya" + "ye" = "ayaye", "ye", "ye" + "ma" + "woo" = "yemawoo"로 3개입니다. 따라서 3을 return합니다.</li></ul><hr style="box-sizing: content-box; height: 0px; overflow: visible; margin: 1.5rem 0px; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; margin: 1.5rem 0px 0px; font-weight: 400; line-height: 1.5; font-size: 15px; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; color: white; letter-spacing: -0.009em;">유의사항</h5><ul style="box-sizing: border-box; margin: 0.75rem 0px 0px; padding-left: 2.5rem;"><li style="box-sizing: border-box; font-size: 16px; letter-spacing: -0.009em; line-height: 1.6; list-style: inherit;">네 가지를 붙여 만들 수 있는 발음 이외에는 어떤 발음도 할 수 없는 것으로 규정합니다. 예를 들어 "woowo"는 "woo"는 발음할 수 있지만 "wo"를 발음할 수 없기 때문에 할 수 없는 발음입니다.</li></ul></div></div></div></div></div></div>
</body>
</html>

https://school.programmers.co.kr/tryouts/85889/challenges

**Comment by gka0903** [comment]
https://school.programmers.co.kr/learn/courses/30/lessons/120956
