### ISSUE TITLE
[코테] 1이 될 때까지

### ISSUE THREAD

**Issue by JungHanLeee** [Team-Discipline/Coding-Test#242]
[ 문제 ] 1이 될 때까지

어떠한 수 N이 1이 될 때까지 다음의 두 과정 중 하나를 반복적으로 선택하여 수행하려고 한다.

단, 두번째 연산은 N이 K로 나누어 떨어질 때만 선택할 수 있다.

1. N에서 1을 뺀다.
2. N을 K로 나눈다.
N과 K가 주어질 때 N이 1이 될 때까지 1번 혹은 2번의 과정을 수행해야 하는 최소 횟수를 구하는 프로그램을 작성하라.
![image](https://github.com/Team-Discipline/Coding-Test/assets/89134202/5367ff32-60a3-4f36-8166-e3db115b4542)

**Comment by gka0903** [comment]
링크좀

**Comment by kreimben** [comment]
이런거 우리 많이 푼거 같은데...
