### ISSUE TITLE
[코테] 주차 요금 계산

### ISSUE THREAD

**Issue by JungHanLeee** [Team-Discipline/Coding-Test#72]
<h5 style="font-style: normal; font-variant-caps: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px; margin: 0px; color: white; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-size: 15px; font-weight: 400; font-stretch: inherit; line-height: 1.5; letter-spacing: -0.009em; text-align: left;">문제 설명</h5><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: rgb(178, 192, 204); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-stretch: inherit; line-height: 1.8; letter-spacing: -0.1px; overflow-wrap: break-word; caret-color: rgb(178, 192, 204); text-align: left;">주차장의 요금표와 차량이 들어오고(입차) 나간(출차) 기록이 주어졌을 때, 차량별로 주차 요금을 계산하려고 합니다. 아래는 하나의 예시를 나타냅니다.</p><ul style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 1rem 0px 0px; color: rgb(178, 192, 204); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-stretch: inherit; line-height: inherit; caret-color: rgb(178, 192, 204); text-align: left;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-family: inherit; font-size: 16px; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.6; letter-spacing: -0.009em; list-style: inherit;"><strong style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-family: inherit; font-size: inherit; font-style: inherit; font-variant-caps: inherit; font-weight: bolder; font-stretch: inherit; line-height: inherit; -webkit-font-smoothing: antialiased;">요금표</strong></li></ul>

기본 시간(분) | 기본 요금(원) | 단위 시간(분) | 단위 요금(원)
-- | -- | -- | --
180 | 5000 | 10 | 600

<ul style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 0.75rem 0px 0px; color: rgb(178, 192, 204); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-stretch: inherit; line-height: inherit; caret-color: rgb(178, 192, 204); text-align: left;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-family: inherit; font-size: 16px; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.6; letter-spacing: -0.009em; list-style: inherit;"><code style="box-sizing: border-box; padding: 2px 6px; margin: 0px 2px 0px 0px; color: rgb(205, 215, 224); font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-size: 14px; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; overflow-wrap: break-word; border: 1px solid rgb(23, 35, 52); background-color: rgb(32, 43, 61); border-radius: 0.25rem;">1234</code>번 차량은 출차 내역이 없으므로, 23:59에 출차되었다고 간주합니다.</li></ul><hr style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: content-box; padding: 0px; margin: 1.5rem 0px; color: rgb(178, 192, 204); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-stretch: inherit; line-height: inherit; height: 0px; overflow: visible; border-width: 0.0625rem 0px 0px; border-color: rgb(23, 35, 52); border-top-style: solid; caret-color: rgb(178, 192, 204); text-align: left;"><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: rgb(178, 192, 204); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-stretch: inherit; line-height: 1.8; letter-spacing: -0.1px; overflow-wrap: break-word; caret-color: rgb(178, 192, 204); text-align: left;">​</p><h5 style="font-style: normal; font-variant-caps: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px; margin: 1.5rem 0px 0px; color: white; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-size: 15px; font-weight: 400; font-stretch: inherit; line-height: 1.5; letter-spacing: -0.009em; text-align: left;">제한시간 안내</h5><ul style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 0.75rem 0px 0px; color: rgb(178, 192, 204); font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-stretch: inherit; line-height: inherit; caret-color: rgb(178, 192, 204); text-align: left;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-family: inherit; font-size: 16px; font-style: inherit; font-variant-caps: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.6; letter-spacing: -0.009em; list-style: inherit;">정확성 테스트 : 10초</li></ul>

https://school.programmers.co.kr/learn/courses/30/lessons/92341

**Comment by kreimben** [comment]
중복
