### ISSUE TITLE
[코테] 롤케이크 자르기

### ISSUE THREAD

**Issue by JungHanLeee** [Team-Discipline/Coding-Test#93]
<html>
<body>
<ul class="challenge-nav nav nav-tabs nav-tabs-dark task-tab" id="tab" role="tablist" style="box-sizing: border-box; padding: 0px 1rem; margin: 0px; color: rgb(38, 55, 71); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; display: flex; flex-wrap: wrap; list-style: none; border-bottom: 0px; box-shadow: rgb(23, 35, 52) 0px -0.0625rem inset; background-color: rgb(38, 55, 71); position: relative; justify-content: space-between; height: 3.5rem; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="nav-item algorithm-nav-link algorithm-title" style="box-sizing: border-box; padding: 0.9375rem 0px 0px; margin: 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 16px; line-height: 1.6; font-family: inherit; letter-spacing: -0.009em;">롤케이크 자르기</li><div class="challenge-settings nav-item" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0px 1rem; color: inherit; font: inherit; display: flex; align-items: center; justify-content: flex-end; height: 3rem;"><div class="btn-group-theme btn-group btn-group-toggle" data-toggle="buttons" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0px 0.5rem; color: inherit; font: inherit; position: relative; display: inline-flex; vertical-align: middle;"><label class="btn btn-sm btn-outline-dark active" style="box-sizing: border-box; padding: 0.125rem 0.375rem; margin: 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: 500; font-stretch: inherit; font-size: 0.75rem; line-height: 1.125rem; font-family: inherit; display: inline-block; text-align: center; vertical-align: middle; user-select: none; background-color: rgb(68, 87, 108); border: 1px solid rgb(68, 87, 108); border-radius: 0.2rem 0px 0px 0.2rem; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; z-index: 1;"><input type="radio" name="themes" autocomplete="off" checked="" data-toggle="button" data-theme="dark" style="box-sizing: border-box; padding: 0px; margin: 0px 0.375rem 0px 0px; color: inherit; font: inherit; overflow: visible; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.32rem solid rgb(38, 55, 71); appearance: none; background-color: white !important; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">dark</label><label class="btn btn-sm btn-outline-dark" style="box-sizing: border-box; padding: 0.125rem 0.375rem; margin: 0px 0px 0px -1px; color: rgb(68, 87, 108); font-style: inherit; font-variant: inherit; font-weight: 500; font-stretch: inherit; font-size: 0.75rem; line-height: 1.125rem; font-family: inherit; display: inline-block; text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(68, 87, 108); border-radius: 0px 0.2rem 0.2rem 0px; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto;"><input type="radio" name="themes" autocomplete="off" data-toggle="button" data-theme="light" style="box-sizing: border-box; padding: 0px; margin: 0px 0.375rem 0px 0px; color: inherit; font: inherit; overflow: visible; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.125rem solid rgb(178, 192, 204); appearance: none; background-color: transparent; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">light</label></div><div data-toggle="popover" data-trigger="hover" data-placement="bottom" data-content="코드 에디터의 단축키를 설정하는 옵션입니다. 선호하는 에디터 옵션이 없다면 sublime을 선택해주세요." data-original-title="" title="" style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font: inherit;"><div class="btn-group-keymap btn-group btn-group-toggle" data-toggle="buttons" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0px 0.5rem; color: inherit; font: inherit; position: relative; display: inline-flex; vertical-align: middle;"><label class="btn btn-sm btn-outline-dark active" style="box-sizing: border-box; padding: 0.125rem 0.375rem; margin: 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: 500; font-stretch: inherit; font-size: 0.75rem; line-height: 1.125rem; font-family: inherit; display: inline-block; text-align: center; vertical-align: middle; user-select: none; background-color: rgb(68, 87, 108); border: 1px solid rgb(68, 87, 108); border-radius: 0.2rem 0px 0px 0.2rem; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto; z-index: 1;"><input type="radio" name="keymaps" autocomplete="off" checked="" data-keymap="sublime" style="box-sizing: border-box; padding: 0px; margin: 0px 0.375rem 0px 0px; color: inherit; font: inherit; overflow: visible; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.32rem solid rgb(38, 55, 71); appearance: none; background-color: white !important; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">sublime</label><label class="btn btn-sm btn-outline-dark" style="box-sizing: border-box; padding: 0.125rem 0.375rem; margin: 0px 0px 0px -1px; color: rgb(68, 87, 108); font-style: inherit; font-variant: inherit; font-weight: 500; font-stretch: inherit; font-size: 0.75rem; line-height: 1.125rem; font-family: inherit; display: inline-block; text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(68, 87, 108); border-radius: 0px; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto;"><input type="radio" name="keymaps" autocomplete="off" data-keymap="vim" style="box-sizing: border-box; padding: 0px; margin: 0px 0.375rem 0px 0px; color: inherit; font: inherit; overflow: visible; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.125rem solid rgb(178, 192, 204); appearance: none; background-color: transparent; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">vim</label><label class="btn btn-sm btn-outline-dark" style="box-sizing: border-box; padding: 0.125rem 0.375rem; margin: 0px 0px 0px -1px; color: rgb(68, 87, 108); font-style: inherit; font-variant: inherit; font-weight: 500; font-stretch: inherit; font-size: 0.75rem; line-height: 1.125rem; font-family: inherit; display: inline-block; text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(68, 87, 108); border-radius: 0px 0.2rem 0.2rem 0px; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; cursor: pointer; position: relative; flex: 1 1 auto;"><input type="radio" name="keymaps" autocomplete="off" data-keymap="emacs" style="box-sizing: border-box; padding: 0px; margin: 0px 0.375rem 0px 0px; color: inherit; font: inherit; overflow: visible; cursor: pointer; width: 1rem; min-width: 1rem; max-width: 1rem; height: 1rem; border: 0.125rem solid rgb(178, 192, 204); appearance: none; background-color: transparent; border-radius: 62.5rem; vertical-align: middle; outline: none !important; position: absolute; clip: rect(0px, 0px, 0px, 0px); pointer-events: none;">emacs</label></div></div><div class="dropdown-language" id="tour7" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0px 0.5rem; color: inherit; font: inherit;"><button class="btn btn-sm btn-dark dropdown-toggle" type="button" data-toggle="dropdown" style="box-sizing: border-box; padding: 0.125rem 0.375rem; margin: 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: 500; font-stretch: inherit; font-size: 0.75rem; line-height: 1.125rem; font-family: inherit; border-radius: 0.2rem; overflow: visible; text-transform: none; appearance: button; border: 1px solid rgb(68, 87, 108); background: none rgb(68, 87, 108); cursor: pointer; display: inline-block; text-align: center; vertical-align: middle; user-select: none; transition: color 0.08s ease-in-out 0s, background-color 0.08s ease-in-out 0s, border-color 0.08s ease-in-out 0s, box-shadow 0.08s ease-in-out 0s; white-space: nowrap;">Python3<span> </span></button></div></div></ul><div class="challenge-content lesson-algorithm-main-section " data-challengeable-id="13899" data-challengeable-type="algorithm" data-algorithm-type="standard" data-language="python3" data-user-id="363214" data-interface-type="function" style="box-sizing: border-box; padding: 0px; margin: 0px; color: rgb(38, 55, 71); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; min-height: 31.25rem; background-color: rgb(38, 55, 71); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="main-section false" style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font: inherit; display: flex; flex-direction: row; height: calc(100vh - 10rem);"><div class="guide-section false" id="tour2" style="box-sizing: border-box; padding: 1rem; margin: 0px; color: inherit; font: inherit; overflow-y: auto; background-color: rgb(38, 55, 71); width: calc(40% - 12px);"><div class="guide-section-description" style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font: inherit;"><h6 class="guide-section-title" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1rem; color: white; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; -webkit-font-smoothing: antialiased;">문제 설명</h6><div class="markdown solarized-dark" style="box-sizing: border-box; padding: 0px; margin: 0px; color: rgb(178, 192, 204); font: inherit; background-color: transparent; word-break: normal; overflow-wrap: break-word;"><p style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.1px; overflow-wrap: break-word;">철수는 롤케이크를 두 조각으로 잘라서 동생과 한 조각씩 나눠 먹으려고 합니다. 이 롤케이크에는 여러가지 토핑들이 일렬로 올려져 있습니다. 철수와 동생은 롤케이크를 공평하게 나눠먹으려 하는데, 그들은 롤케이크의 크기보다 롤케이크 위에 올려진 토핑들의 종류에 더 관심이 많습니다. 그래서 잘린 조각들의 크기와 올려진 토핑의 개수에 상관없이 각 조각에 동일한 가짓수의 토핑이 올라가면 공평하게 롤케이크가 나누어진 것으로 생각합니다.</p><p style="box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.1px; overflow-wrap: break-word;">예를 들어, 롤케이크에 4가지 종류의 토핑이 올려져 있다고 합시다. 토핑들을 1, 2, 3, 4와 같이 번호로 표시했을 때, 케이크 위에 토핑들이 [1, 2, 1, 3, 1, 4, 1, 2] 순서로 올려져 있습니다. 만약 세 번째 토핑(1)과 네 번째 토핑(3) 사이를 자르면 롤케이크의 토핑은 [1, 2, 1], [3, 1, 4, 1, 2]로 나뉘게 됩니다. 철수가 [1, 2, 1]이 놓인 조각을, 동생이 [3, 1, 4, 1, 2]가 놓인 조각을 먹게 되면 철수는 두 가지 토핑(1, 2)을 맛볼 수 있지만, 동생은 네 가지 토핑(1, 2, 3, 4)을 맛볼 수 있으므로, 이는 공평하게 나누어진 것이 아닙니다. 만약 롤케이크의 네 번째 토핑(3)과 다섯 번째 토핑(1) 사이를 자르면 [1, 2, 1, 3], [1, 4, 1, 2]로 나뉘게 됩니다. 이 경우 철수는 세 가지 토핑(1, 2, 3)을, 동생도 세 가지 토핑(1, 2, 4)을 맛볼 수 있으므로, 이는 공평하게 나누어진 것입니다. 공평하게 롤케이크를 자르는 방법은 여러가지 일 수 있습니다. 위의 롤케이크를 [1, 2, 1, 3, 1], [4, 1, 2]으로 잘라도 공평하게 나뉩니다. 어떤 경우에는 롤케이크를 공평하게 나누지 못할 수도 있습니다.</p><p style="box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.1px; overflow-wrap: break-word;">롤케이크에 올려진 토핑들의 번호를 저장한 정수 배열<span> </span><code style="box-sizing: border-box; padding: 2px 6px; margin: 0px 2px 0px 0px; color: rgb(205, 215, 224); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; overflow-wrap: break-word; border: 1px solid rgb(23, 35, 52); background-color: rgb(32, 43, 61); border-radius: 0.25rem;">topping</code>이 매개변수로 주어질 때, 롤케이크를 공평하게 자르는 방법의 수를 return 하도록 solution 함수를 완성해주세요.</p><hr style="box-sizing: content-box; padding: 0px; margin: 1.5rem 0px; color: inherit; font: inherit; height: 0px; overflow: visible; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; padding: 0px; margin: 1.5rem 0px 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.009em;">제한사항</h5><ul style="box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 0.75rem 0px 0px; color: inherit; font: inherit;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 16px; line-height: 1.6; font-family: inherit; letter-spacing: -0.009em; list-style: inherit;">1 ≤<span> </span><code style="box-sizing: border-box; padding: 2px 6px; margin: 0px 2px 0px 0px; color: rgb(205, 215, 224); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; overflow-wrap: break-word; border: 1px solid rgb(23, 35, 52); background-color: rgb(32, 43, 61); border-radius: 0.25rem;">topping</code>의 길이 ≤ 1,000,000<ul style="box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 0.75rem 0px 0px; color: inherit; font: inherit;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 16px; line-height: 1.6; font-family: inherit; letter-spacing: -0.009em; list-style: inherit;">1 ≤<span> </span><code style="box-sizing: border-box; padding: 2px 6px; margin: 0px 2px 0px 0px; color: rgb(205, 215, 224); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; overflow-wrap: break-word; border: 1px solid rgb(23, 35, 52); background-color: rgb(32, 43, 61); border-radius: 0.25rem;">topping</code>의 원소 ≤ 10,000</li></ul></li></ul><hr style="box-sizing: content-box; padding: 0px; margin: 1.5rem 0px; color: inherit; font: inherit; height: 0px; overflow: visible; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; padding: 0px; margin: 1.5rem 0px 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.009em;">입출력 예</h5>

topping | result
-- | --
[1, 2, 1, 3, 1, 4, 1, 2] | 2
[1, 2, 3, 1, 4] | 0

<hr style="box-sizing: content-box; padding: 0px; margin: 1.5rem 0px; color: inherit; font: inherit; height: 0px; overflow: visible; border-width: 0.0625rem 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-color: rgb(23, 35, 52); border-image: initial; border-top-style: solid;"><h5 style="box-sizing: border-box; padding: 0px; margin: 1.5rem 0px 0px; color: white; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.009em;">입출력 예 설명</h5><p style="box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.1px; overflow-wrap: break-word;"><strong style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; -webkit-font-smoothing: antialiased;">입출력 예 #1</strong></p><ul style="box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 1rem 0px 0px; color: inherit; font: inherit;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 16px; line-height: 1.6; font-family: inherit; letter-spacing: -0.009em; list-style: inherit;">롤케이크를 [1, 2, 1, 3], [1, 4, 1, 2] 또는 [1, 2, 1, 3, 1], [4, 1, 2]와 같이 자르면 철수와 동생은 각각 세 가지 토핑을 맛볼 수 있습니다. 이 경우 공평하게 롤케이크를 나누는 방법은 위의 두 가지만 존재합니다.</li></ul><p style="box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.1px; overflow-wrap: break-word;"><strong style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: bolder; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; -webkit-font-smoothing: antialiased;">입출력 예 #2</strong></p><ul style="box-sizing: border-box; padding: 0px 0px 0px 2.5rem; margin: 1rem 0px 0px; color: inherit; font: inherit;"><li style="box-sizing: border-box; padding: 0px; margin: 0px; color: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 16px; line-height: 1.6; font-family: inherit; letter-spacing: -0.009em; list-style: inherit;">롤케이크를 공평하게 나눌 수 없습니다.</li></ul></div></div></div></div></div>
</body>
</html>

https://school.programmers.co.kr/learn/courses/30/lessons/132265

**Comment by kreimben** [comment]
- [ ] 시간부족 해결법 설명
